apiVersion: apps/v1
kind: Deployment
metadata:
  name: tugaspntdeploy
  labels:
    app: tugaspntdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tugaspntdeploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tugaspntdeploy
    spec:
      containers:
      - name: tugaspntdeploy-container
        image: juansaputro/pnt-tugas1:v0.0
        ports:
        - containerPort: 8080